config/routes.rb
Rails.application.routes.draw do

  get 'logins/index'

  get 'clientes/perfil'

  get 'logins/sair'

  get 'funcionarios/perfil'

  get 'padrao/contato'

  resources :funcionarios
  resources :contums
  resources :clientes
  resources :pagamentos
  resources :logins

  root 'logins#index'

end

app/models/cliente.rb
class Cliente < Pessoa

  def self.pesquisa query
    clientes = listaClientes
    pesquisaIds = clientes.pesquisaId(query)
    pesquisaCpfs = clientes.pesquisaCpf(query)
    pesquisaNomes = clientes.pesquisaNome(query)
    resultado = []
    pesquisaIds.each do |cliente|
      resultado << cliente
    end
    pesquisaCpfs.each do |cliente|
      if(!resultado.index(cliente))
        resultado << cliente
      end
    end
    pesquisaNomes.each do |cliente|
      if(!resultado.index(cliente))
        resultado << cliente
      end
    end
    resultado
  end

  def self.buscarClientePorCpf cpf
    clientes = listaClientes
    clientes.each do |cliente|
      if cliente.cpf == cpf
        return cliente
      end
    end
    return nil
  end

  scope :listaClientes, -> { where("inativo like ?", "%#{0}%") }
  scope :pesquisaId, ->(query) { where("id like ?", "%#{query}%") }
  scope :pesquisaCpf, ->(query) { where("cpf like ?", "%#{query}%") }
  scope :pesquisaNome, ->(query) { where("nome like ?", "%#{query}%") }

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  respond_to :js, :html

  def perfil
    if segurancaLogin(0)
      @cliente = Pessoa.getPessoaLogada()
      @contasPagas = []
      @contasDevendo = []
      @contasAtrasadas = []
      if !@cliente.id.nil?
        carregarContas(@cliente.id)
      end
    end
  end

  def index
    segurancaLogin(1)
    @cliente = Cliente.new
    carregar_tabela(params[:pesquisa])
  end

  def new
    segurancaLogin(1)
    @cliente = Cliente.new
  end

  def edit
    segurancaLogin(1)
    @cliente = Cliente.find(params[:id])
    @clientes = Cliente.listaClientes
    render 'clientes/index'
  end

  def update
    segurancaLogin(1)
    @cliente = Cliente.find(params[:id])


    if @cliente.update(cliente_params)
      carregar_tabela('')
      @resultadoCliente = "Cliente Atualizado"
    else
      carregar_tabela('')
      @resultadoCliente = "erro-"
    end

  end

  def create
    segurancaLogin(1)
    @cliente = Cliente.new(cliente_params)
    # tipo = 0 é cliente e. tipo = 1 é funcionario
    @cliente.tipo = 0
    @cliente.inativo = 0

    if @cliente.save
      #carregar_tabela ''
      @resultadoCliente = "Cliente Salvo"
      redirect_to
    else
      @resultadoCliente = "erro-"
    end
  end

  def destroy
    segurancaLogin(1)
    @cliente = Cliente.find(params[:id])
    if !verificar_contas_cliente @cliente.id
      @cliente.update(inativo: 1)
      carregar_tabela ''
      @resultadoCliente = "Cliente Deletado";
    else
      @resultadoCliente = "erro-O cliente não foi deletado pois ele está devendo contas";
    end
  end

  private

  def segurancaLogin pessoa
    resultado = true
    if pessoa == 1
      if Pessoa.getPessoaLogada().nil? || Pessoa.getPessoaLogada().tipo != 1
        resultado = false
        redirect_to logins_path
      end
    else
      if Pessoa.getPessoaLogada().nil? || Pessoa.getPessoaLogada().tipo != 0
        resultado = false
        redirect_to logins_path
      end
    end
    resultado
  end

  def carregarContas id
    contas = Contum.listaContasCliente(id)
    @contasDevendo = contas.listaContasDevendo
    @contasAtrasadas = contas.listaContasAtrasadas
    @contasPagas = contas.listaContasPagas
  end

  def cliente_params
    params.require(:cliente).permit(:nome, :cpf, :telefone, :celular, :email, :senha, :cidade, :rua, :numero)
  end

  def carregar_tabela (pesquisa)
    if pesquisa && pesquisa != ''
      @clientes = Cliente.pesquisa(pesquisa)
    else
      @clientes = Cliente.listaClientes
    end
  end

  def verificar_contas_cliente id
    contas = Contum.listaContasCliente(id)
    contasDevendo = contas.listaContasDevendo
    contasAtrasadas = contas.listaContasAtrasadas
    resultado = false
    if contasDevendo.count > 0 || contasAtrasadas.count > 0
      resultado = true
    end
    resultado
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/create.js.erb
<% if(@resultadoCliente) %>

  <%
     valorCor = ""
     valorId = "resultadoPositivo"
     resultado = @resultadoCliente
    if resultado.split('-')[0] == 'erro'
      valorCor = "color: red"
      valorId = "resultadoNegativo"
      resultado = resultado.split('-')[1]
    end
  %>

  var div = document.getElementById('resultadoCliente');

  <%if valorId == "resultadoPositivo"%>
    document.getElementById('FormularioCliente').reset();
    div.innerHTML = "<span id='<%=valorId%>' style='<%=valorCor%>'><%=resultado%></span>";

    var tabelaCliente = document.getElementById('tabelaCliente');
    tabelaCliente.innerHTML = '';

    <% @clientes.each do |cliente| %>

      <% if cliente.cargo != "gerente" %>
      tabelaCliente.innerHTML = tabelaCliente.innerHTML +
          "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
          "<div class='left col-1 colunaCorpoComum colunaId'> <%= cliente.id %> </div>" +
          "<div class='left col-1 colunaCorpoComum colunaNome'> <%= cliente.nome %> </div>" +
          "<div class='left col-5 colunaCorpoComum colunaCpf'> <%= cliente.cpf %> </div>" +
          "<div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
          "<a href=<%=edit_cliente_path(cliente)%> class='botao_tabela' id=<%="d-#{'edit-'+cliente.cpf}"%> >Editar</a>" +
          "</div><div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
          "<a class='botao_tabela' data-remote='true' id=<%="d-#{'delete-'+cliente.cpf}"%> data-confirm='Tem certeza que deseja excluir esse Cliente?' rel='nofollow' data-method='delete' href=<%= cliente_path(cliente) %>>Deletar</a>" +
          "</div></div>";
      <%end %>

    <% end %>
  <%else %>
    <% if @cliente.errors.any? %>
      div.innerHTML = "<h2 style='<%=valorCor%>; font-size: 18px;'><%= pluralize(@cliente.errors.count, 'erros') %> antes de criar o cliente:</h2><ul>";
      var result = "";
      <%@cliente.errors.full_messages.each do |msg|%>
          result += "<li style='<%=valorCor%>; font-size: 17px;'><%= msg %></li>";
      <% end %>
      div.innerHTML += result + "</ul>";
    <% end %>
  <%end %>

<%end %>

app/views/clientes/destroy.js.erb
<% if(@resultadoCliente) %>

  <%
     valorCor = ""
     valorId = "resultadoPositivo"
     resultado = @resultadoCliente
    if resultado.split('-')[0] == 'erro'
      valorCor = "color: red"
      valorId = "resultadoNegativo"
      resultado = resultado.split('-')[1]
    end
  %>

  var div = document.getElementById('resultadoCliente');
  div.innerHTML = "<span id='<%=valorId%>' style='<%=valorCor%>'><%=resultado%></span>";

  <%if valorId == "resultadoPositivo"%>

    var tabelaCliente = document.getElementById('tabelaCliente');
    tabelaCliente.innerHTML = '';

    <% @clientes.each do |cliente| %>

    <% if cliente.cargo != "gerente" %>
    tabelaCliente.innerHTML = tabelaCliente.innerHTML +
        "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
        "<div class='left col-1 colunaCorpoComum colunaId'> <%= cliente.id %> </div>" +
        "<div class='left col-1 colunaCorpoComum colunaNome'> <%= cliente.nome %> </div>" +
        "<div class='left col-5 colunaCorpoComum colunaCpf'> <%= cliente.cpf %> </div>" +
        "<div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
        "<a href=<%=edit_cliente_path(cliente)%> class='botao_tabela' id=<%="d-#{'edit-'+cliente.cpf}"%> >Editar</a>" +
        "</div><div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
        "<a class='botao_tabela' data-remote='true' id=<%="d-#{'delete-'+cliente.cpf}"%> data-confirm='Tem certeza que deseja excluir esse Cliente?' rel='nofollow' data-method='delete' href=<%= cliente_path(cliente) %>>Deletar</a>" +
        "</div></div>";
    <%end %>

    <% end %>

  <%end %>

<%end %>

app/views/clientes/index.html.erb
<body>
<div id="wrap">
  <div id="masthead">
    <h1>Sistema Financeiro de Supermecado - Mercado São Caetano</h1>
    <h2><%= link_to 'Perfil', funcionarios_perfil_path %> | <%= link_to 'Contato', padrao_contato_path %> | <%= link_to 'Sair', logins_sair_path %> </h2>
  </div>
  <div id="menucontainer">
    <div id="menu">
      <ul>
        <li><%= link_to 'Registro', new_contum_path %></li>
        <li><%= link_to 'Pagamento', pagamentos_path %></li>
        <li><%= link_to 'Contas', contums_path %></li>
        <li><%= link_to 'Cliente', clientes_path, class:"current"%></li>
        <%if Pessoa.getPessoaLogada.cargo == "gerente" %>
          <li><%= link_to 'Funcionário', funcionarios_path %></li>
        <%end%>
      </ul>
    </div>
  </div>
  <div id="container">

    <div id="content">

      <% # formulario de cadastramento ..................................... %>
      <%= form_with model: @cliente, local:true, scope: :cliente, id:"FormularioCliente", class:"formulario" do |form| %>

        <span class="titulo_formulario">
					Cadastrar Cliente
				</span>


        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :nome, class:"label-elemento_formulario" %><br>
          <%= form.text_field :nome, class:"input100", placeholder:"Digite um nome" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cpf, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cpf, class:"input100", placeholder:"Digite um cpf" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :telefone, class:"label-elemento_formulario" %><br>
          <%= form.text_field :telefone, class:"input100", placeholder:"Digite um número de telefone" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :celular, class:"label-elemento_formulario" %><br>
          <%= form.text_field :celular, class:"input100", placeholder:"Digite um número de celular" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :email, class:"label-elemento_formulario" %><br>
          <%= form.text_field :email, class:"input100", placeholder:"Digite um e-mail (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :senha, class:"label-elemento_formulario" %><br>
          <%= form.text_field :senha, type:"password", class:"input100", placeholder:"Digite uma senha (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cidade, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cidade, class:"input100", placeholder:"Digite o nome de uma cidade/Estado" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :rua, class:"label-elemento_formulario" %><br>
          <%= form.text_field :rua, class:"input100", placeholder:"Digite o nome de uma Rua" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :numero, class:"label-elemento_formulario" %><br>
          <%= form.text_field :numero, class:"input100", placeholder:"Digite o número da casa" %>
          <span class="focus-input100"></span>
        </div>

        <div id="resultadoCliente" class='status_processo'></div>

        <div class="div_butao_formulario">
          <button class="botao_formulario">
						<span>
							Adicionar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

      <% end %>

      <% # formulario de pesquisa ......................................... %>
      <%= form_tag(clientes_path, method: :get, remote:true, class:"formulario formulario_pesquisa") do %>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= text_field_tag :pesquisa, nil, class:"input100", placeholder:"Pesquise por nome, cpf e id" %>
          <span class="focus-input100"></span>
        </div>

        <div class="div_butao_formulario" style="margin-top: -70px; margin-left: 380px">
          <button class="botao_tabela" style="height: 50px">
						<span>
							Pesquisar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

      <% end %>

      <% # tabela de cadastramento..................................... %>
      <div class="col-12" >
        <div class="menuTabela col-10 offset-1 row" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaId"> Id </div>
          <div class="left col-5 colunaTituloComum colunaNome"> Nome </div>
          <div class="left col-3 colunaTituloComum colunaCpf"> Cpf </div>
          <div class="left col-3 colunaTituloComum colunaId"></div>
          <div class="left col-3 colunaTituloComum colunaId"></div>
        </div>

        <div id="tabelaCliente" style="height: 500px; overflow-y:auto; overflow-x:hidden;">
          <% @clientes.each do |cliente| %>
            <% if cliente.cargo != "gerente" %>
              <div class="menuTabela col-10 offset-1 row" style="width: 1140px; background: #ffffff;">
                <div class="left col-1 colunaCorpoComum colunaId"> <%= cliente.id %> </div>
                <div class="left col-5 colunaCorpoComum colunaNome"> <%= cliente.nome %> </div>
                <div class="left col-3 colunaCorpoComum colunaCpf"> <%= cliente.cpf %> </div>
                <div class="left col-3" style="width: 10%; font-size: 18px; margin-top: -20px;">
                  <%= link_to 'Editar', edit_cliente_path(cliente), class:"botao_tabela",id:"d-#{'edit-'+cliente.cpf}" %>
                </div>
                <div class="left col-3" style="width: 10%; font-size: 18px; margin-top: -20px;">
                  <%= link_to 'Deletar', cliente_path(cliente), class:"botao_tabela",
                      method: :delete, remote:true,
                      data: { confirm: 'Tem certeza que deseja excluir esse Cliente?' },id:"d-#{'delete-'+cliente.cpf}" %>

                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="footer"> Mercado São Caetano - Centro do povoado Quandu, municipio de Poço de Trincheiras </div>
</div>
</body>

app/views/clientes/index.js.erb
var tabelaCliente = document.getElementById('tabelaCliente');
tabelaCliente.innerHTML = '';

<% @clientes.each do |cliente| %>
  <% if cliente.cargo != "gerente" %>
  tabelaCliente.innerHTML = tabelaCliente.innerHTML +
      "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
      "<div class='left col-1 colunaCorpoComum colunaId'> <%= cliente.id %> </div>" +
      "<div class='left col-1 colunaCorpoComum colunaNome'> <%= cliente.nome %> </div>" +
      "<div class='left col-5 colunaCorpoComum colunaCpf'> <%= cliente.cpf %> </div>" +
      "<div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
      "<a href=<%=edit_cliente_path(cliente)%> class='botao_tabela' id=<%="d-#{'edit-'+cliente.cpf}"%> >Editar</a>" +
      "</div><div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
      "<a class='botao_tabela' data-remote='true' id=<%="d-#{'delete-'+cliente.cpf}"%> data-confirm='Tem certeza que deseja excluir esse Cliente?' rel='nofollow' data-method='delete' href=<%= cliente_path(cliente) %>>Deletar</a>" +
      "</div></div>";
  <%end %>
<% end %>

app/views/clientes/perfil.html.erb
<body>
<div id="wrap">
  <div id="masthead">
    <h1>Sistema Financeiro de Supermecado - Mercado São Caetano</h1>
    <h2><%= link_to 'Contato', padrao_contato_path %> | <%= link_to 'Sair', logins_sair_path %> </h2>
  </div>
  <div id="container">

    <div id="content">

      <span class="titulo_formulario" style="margin-top: 40px; margin-bottom: 30px">
					Perfil do Cliente <%= @cliente.nome %>
      </span>

      <% # tabela de contas atrazadas..................................... %>
      <textarea readonly=“true” id="contasAtrasada" class="titulo_formulario" style="font-size: 30px"></textarea>
      <script>somarContasAtrasadasCliente(0)</script>
      <div class="col-12" style="width: 1140px" >
        <div class="menuTabela" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaIdConta"> Id </div>
          <div class="left col-1 colunaTituloComum colunaCliente"> Funcionário </div>
          <div class="left col-5 colunaTituloComum colunaDescricao"> Descrição </div>
          <div class="left col-3 colunaTituloComum colunaValor"> Valor </div>
          <div class="left col-3 colunaTituloComum colunaData"> Data de Compra </div>
          <div class="left col-3 colunaTituloComum " style="width: 12.6%"></div>
        </div>

        <div id="tabelaContasAtrasadas" style="width: 1200px; height: 200px; overflow-y:auto; overflow-x:hidden;">
          <%
            cont = @contasAtrasadas.count - 1
             while(cont >= 0)
          %>
            <div class="menuTabela" style="width: 1140px; background: #ffffff;">
              <div class="left col-1 colunaCorpoComum colunaIdConta"> <%= @contasAtrasadas[cont].id %> </div>
              <div class="left col-1 colunaCorpoComum colunaCliente"> <%= Funcionario.pesquisaId(@contasAtrasadas[cont].funcionario)[0].nome %> </div>
              <div class="left col-5 colunaCorpoComum colunaDescricao"> <%= @contasAtrasadas[cont].descricao %> </div>
              <%if @contasAtrasadas[cont].juros > 0
                  @contasAtrasadas[cont].valor += (@contasAtrasadas[cont].juros/100) * @contasAtrasadas[cont].valor;
                end
              %>
              <div class="left col-3 colunaCorpoComum colunaValor"> <%= @contasAtrasadas[cont].valor %> </div>
              <%timer = @contasAtrasadas[cont].dataCompra
                data = timer.split(' ')[0].split('-')
                data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
              %>
              <div class="left col-3 colunaCorpoComum colunaData"> <%= data %> </div>
              <div class="left col-3" style="width: 12.6%; font-size: 18px; margin-top: -43px;">
                <input style="zoom: 3;" type="checkbox" id="<%=@contasAtrasadas[cont].id%>" checked='checked' onchange="selecionarContaAtrasadaCliente(<%=@contasAtrasadas[cont].id%>, <%=@contasAtrasadas[cont].valor%>)">
              </div>
            </div>
            <script>somarContasAtrasadasCliente(<%= @contasAtrasadas[cont].valor %>)</script>
          <% cont-= 1
             end %>
        </div>
      </div>

      <% # tabela de contas devendo..................................... %>
      <textarea readonly=“true” id="contasDevendoCliente" class="titulo_formulario" style="font-size: 30px"></textarea>
      <script>somarContasDevendoCliente(0)</script>
      <div class="col-12" style="width: 1140px" >
        <div class="menuTabela" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaIdConta"> Id </div>
          <div class="left col-1 colunaTituloComum colunaCliente"> Funcionário </div>
          <div class="left col-5 colunaTituloComum colunaDescricao"> Descrição </div>
          <div class="left col-3 colunaTituloComum colunaValor"> Valor </div>
          <div class="left col-3 colunaTituloComum colunaData"> Data de Compra </div>
          <div class="left col-3 colunaTituloComum" style="width: 12.6%">Selecionar</div>
        </div>

        <div id="tabelaContasDevendo" style="width: 1200px; height: 200px; overflow-y:auto; overflow-x:hidden;">
          <% cont = @contasDevendo.count - 1
             while(cont >= 0)
          %>
            <div class="menuTabela" style="width: 1140px; background: #ffffff;">
              <div class="left col-1 colunaCorpoComum colunaIdConta"> <%= @contasDevendo[cont].id %> </div>
              <div class="left col-1 colunaCorpoComum colunaCliente"> <%= Funcionario.pesquisaId(@contasDevendo[cont].funcionario)[0].nome %> </div>
              <div class="left col-5 colunaCorpoComum colunaDescricao"> <%= @contasDevendo[cont].descricao %> </div>
              <%if @contasDevendo[cont].juros > 0
                  @contasDevendo[cont].valor += (@contasDevendo[cont].juros/100) * @contasDevendo[cont].valor;
                end
              %>
              <div class="left col-3 colunaCorpoComum colunaValor"> <%= @contasDevendo[cont].valor %> </div>
              <%timer = @contasDevendo[cont].dataCompra
                data = timer.split(' ')[0].split('-')
                data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
              %>
              <div class="left col-3 colunaCorpoComum colunaData"> <%= data %> </div>
              <div class="left col-3" style="width: 12.6%; font-size: 18px; margin-top: -43px;">
                <input style="zoom: 3;" type="checkbox" id="<%=@contasDevendo[cont].id%>" checked='checked' onchange="selecionarContaDevendoCliente(<%=@contasDevendo[cont].id%>, <%=@contasDevendo[cont].valor%>)">
              </div>
            </div>
            <script>somarContasDevendoCliente(<%=@contasDevendo[cont].valor%>)</script>
          <% cont-= 1
             end %>
        </div>
      </div>

      <% # tabela de contas Pagas..................................... %>
      <textarea readonly=“true” id="contasPagas" class="titulo_formulario" style="font-size: 30px"></textarea>
      <script>somarContasPagasCliente(0)</script>
      <div class="col-12" style="width: 1140px" >
        <div class="menuTabela" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaIdConta"> Id </div>
          <div class="left col-1 colunaTituloComum colunaCliente"> Funcionário </div>
          <div class="left col-5 colunaTituloComum colunaDescricao"> Descrição </div>
          <div class="left col-3 colunaTituloComum colunaValor"> Valor </div>
          <div class="left col-3 colunaTituloComum colunaData"> Data de Compra </div>
          <div class="left col-3 colunaTituloComum" style="width: 12.6%">Selecionar</div>
        </div>

        <div id="tabelaContasDevendo" style="width: 1200px; height: 200px; overflow-y:auto; overflow-x:hidden;">
          <% cont = @contasPagas.count - 1
             while(cont >= 0)
          %>
            <div class="menuTabela" style="width: 1140px; background: #ffffff;">
              <div class="left col-1 colunaCorpoComum colunaIdConta"> <%= @contasPagas[cont].id %> </div>
              <div class="left col-1 colunaCorpoComum colunaCliente"> <%= Funcionario.pesquisaId(@contasPagas[cont].funcionario)[0].nome %> </div>
              <div class="left col-5 colunaCorpoComum colunaDescricao"> <%= @contasPagas[cont].descricao %> </div>
              <%if @contasPagas[cont].juros > 0
                  @contasPagas[cont].valor += (@contasPagas[cont].juros/100) * @contasPagas[cont].valor;
                end
              %>
              <div class="left col-3 colunaCorpoComum colunaValor"> <%= @contasPagas[cont].valor %> </div>
              <%timer = @contasPagas[cont].dataCompra
                data = timer.split(' ')[0].split('-')
                data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
              %>
              <div class="left col-3 colunaCorpoComum colunaData"> <%= data %> </div>
              <div class="left col-3" style="width: 12.6%; font-size: 18px; margin-top: -43px;">
                <input style="zoom: 3;" type="checkbox" id="<%=@contasPagas[cont].id%>" checked='checked' onchange="selecionarContaPagasCliente(<%=@contasPagas[cont].id%>, <%=@contasPagas[cont].valor%>)">
              </div>
            </div>
            <script>somarContasPagasCliente(<%= @contasPagas[cont].valor %>)</script>
          <% cont-= 1
             end %>
        </div>
      </div>

    </div>

  </div>
  <div id="footer"> Informações Sobre o Mercado </div>
</div>
</body>

app/views/clientes/update.js.erb
<% if(@resultadoCliente) %>

  <%
     valorCor = ""
     valorId = "resultadoPositivo"
     resultado = @resultadoCliente
    if resultado.split('-')[0] == 'erro'
      valorCor = "color: red"
      valorId = "resultadoNegativo"
      resultado = resultado.split('-')[1]
    end
  %>

  var div = document.getElementById('resultadoCliente');

  <%if valorId == "resultadoPositivo"%>
    div.innerHTML = "<span id='<%=valorId%>' style='<%=valorCor%>'><%=resultado%></span>";
    var tabelaCliente = document.getElementById('tabelaCliente');
    tabelaCliente.innerHTML = '';

    <% @clientes.each do |cliente| %>

      <% if cliente.cargo != "gerente" %>
      tabelaCliente.innerHTML = tabelaCliente.innerHTML +
          "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
          "<div class='left col-1 colunaCorpoComum colunaId'> <%= cliente.id %> </div>" +
          "<div class='left col-1 colunaCorpoComum colunaNome'> <%= cliente.nome %> </div>" +
          "<div class='left col-5 colunaCorpoComum colunaCpf'> <%= cliente.cpf %> </div>" +
          "<div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
          "<a href=<%=edit_cliente_path(cliente)%> class='botao_tabela' id=<%="d-#{'edit-'+cliente.cpf}"%> >Editar</a>" +
          "</div><div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
          "<a class='botao_tabela' data-remote='true' id=<%="d-#{'delete-'+cliente.cpf}"%> data-confirm='Tem certeza que deseja excluir esse Cliente?' rel='nofollow' data-method='delete' href=<%= cliente_path(cliente) %>>Deletar</a>" +
          "</div></div>";
      <%end %>
    <%end %>
  <%else %>
    <% if @cliente.errors.any? %>
      div.innerHTML = "<h2 style='<%=valorCor%>; font-size: 18px;'><%= pluralize(@cliente.errors.count, 'erros') %> antes de criar o cliente:</h2><ul>";
      var result = "";
      <%@cliente.errors.full_messages.each do |msg|%>
        result += "<li style='<%=valorCor%>; font-size: 17px;'><%= msg %></li>";
      <% end %>
      div.innerHTML += result + "</ul>";
    <% end %>
  <%end %>

<%end %>