config/routes.rb
Rails.application.routes.draw do

  get 'logins/index'

  get 'clientes/perfil'

  get 'logins/sair'

  get 'funcionarios/perfil'

  get 'padrao/contato'

  resources :funcionarios
  resources :contums
  resources :clientes
  resources :pagamentos
  resources :logins

  root 'logins#index'

end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  respond_to :js, :html

  def index
    segurancaLogin(1)
    if(params[:pesquisa] &&  params[:pesquisa] != '')
      @clientes = Cliente.pesquisa(params[:pesquisa])
    else
      @clientes = Cliente.listaClientes
    end

    @contasDevendo = [];
    @contasAtrasadas = [];
    @cliente = Cliente.new
  end

  def show
    segurancaLogin(1)
    carregarContas(params[:id])
    @cliente = Cliente.find(params[:id])
    render 'pagamentos/index'
  end

  def create
    segurancaLogin(1)
    cpf = params[:cpf]
    valorContas = params[:valorContas]
    valorCliente = params[:valorCliente]
    cliente = nil
    if !(cliente = validarDadosPagamento cpf, valorContas, valorCliente).nil?
      valorContas = valorContas.to_f
      valorCliente = valorCliente.to_f
      pagamentoCaso1 params[:idsContasDevendo], params[:idsContasAtrasada], valorCliente, valorContas
      pagamentoCaso2 params[:idsContasDevendo], params[:idsContasAtrasada], valorCliente, valorContas
      carregarContas cliente.id
    end
  end

  private

  def segurancaLogin pessoa
    if pessoa == 1
      if Pessoa.getPessoaLogada().nil? || Pessoa.getPessoaLogada().tipo != 1
        redirect_to logins_path
      end
    else
      if Pessoa.getPessoaLogada().nil? || Pessoa.getPessoaLogada().tipo != 0
        redirect_to logins_path
      end
    end
  end

  # Caso quando o valor dado pelo cliente é maior ou igual do que o valor das contas selecionadas
  def pagamentoCaso1 idsContasDevendo, idsContasAtrasada, valorCliente, valorContas
    if valorCliente >= valorContas
      contas = idsContasAtrasada + idsContasDevendo
      contas = contas.split('-')
      contas.each do |conta|
        if conta != ""
          conta = Contum.find(conta)
          conta.update(status: "Paga", dataPagamento: Time.now.to_s)
        end
      end
      @resultadoPagamento = "Pagamento Efetuado: Troco = " + (valorCliente - valorContas).to_s;
    end
  end

  # Caso quando o valor dado pelo cliente é menor do que o valor das contas selecionadas
  def pagamentoCaso2 idsContasDevendo, idsContasAtrasada, valorCliente, valorContas
    if valorCliente < valorContas
      valorPago = 0
      contas = idsContasAtrasada + idsContasDevendo
      contas = contas.split('-')
      contas.each do |conta|
        if conta != ""
          if valorCliente > valorPago
            conta = Contum.find(conta)
            valor = conta.valor
            if conta.juros > 0
              valor += (conta.juros/100) * valor;
            end
            if (valorCliente - valorPago) >= valor
              conta.update(status: "Paga", dataPagamento: Time.now)
            else
              valor -= (valorCliente - valorPago)
              conta.update(valor: valor)
            end
            valorPago += valor
          end
        end
      end
      @resultadoPagamento = "restante-Pagamento Efetuado: Restante = " + (valorContas - valorCliente).to_s;
    end
  end

  def validarDadosPagamento cpf, valorContas, valorCliente
    resultado = nil
    if verificarVazioOuNulo(cpf) || cpf.length != 11 || !verificarNumeroInt(cpf)
      @resultadoPagamento = "erro-Preenchar um cpf válido"
    elsif verificarVazioOuNulo(valorContas) || valorContas.to_s == '0'
      @resultadoPagamento = "erro-Nenhuma conta foi selecionada"
    elsif verificarVazioOuNulo(valorCliente)
      @resultadoPagamento = "erro-Preencha o valor dado pelo cliente"
    elsif !verificarNumeroFloat(valorCliente)
      @resultadoPagamento = "erro-Preencha um valor dado pelo cliente válido"
    elsif (resultado = Cliente.buscarClientePorCpf cpf) == nil
      @resultadoPagamento = "erro-Esse cliente não existe"
    end
    resultado
  end

  def verificarVazioOuNulo string
    resultado = false
    if string == nil or string == ''
      resultado = true
    end
    resultado
  end

  def verificarNumeroInt string
    resultado = true
    begin
      string = string.to_i
      if string == 0
        resultado = false
      end
    rescue
      resultado = false
    end
    resultado
  end

  def verificarNumeroFloat string
    resultado = true
    begin
      string = string.to_f
      if string == 0
        resultado = false
      end
    rescue
      resultado = false
    end
    resultado
  end

  def carregarContas id
    contas = Contum.listaContasCliente(id)
    @contasDevendo = contas.listaContasDevendo
    @contasAtrasadas = contas.listaContasAtrasadas
    @clientes = Cliente.listaClientes
  end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/views/pagamentos/create.js.erb
<% if(@resultadoPagamento) %>

  <%
     valorCor = ""
     valorId = "resultadoPositivo"
     resultado = @resultadoPagamento
    if resultado.split('-')[0] == 'erro'
      valorCor = "color: red"
      valorId = "resultadoNegativo"
      resultado = resultado.split('-')[1]
    elsif resultado.split('-')[0] == 'restante'
      valorId = "resultadoRestante"
      valorCor = "color: goldenrod"
      resultado = resultado.split('-')[1]
    end
  %>

  var div = document.getElementById('testeDiv');
  div.innerHTML = "<span id='<%=valorId%>' style='<%=valorCor%>'><%=resultado%></span>";

  <%if valorId == "resultadoPositivo" or valorId == "resultadoRestante" %>
    document.getElementById('valorCliente').value = '';
    document.getElementById('valorContas').value = '';

    setValorContaAtrasada(0);
    setValorContaDevendo(0);
    document.getElementById('idsContasAtrasadaSelecionadas').value = '';
    document.getElementById('idsContasDevendoSelecionadas').value = '';

    var tabelaContas = document.getElementById('tabelaContasAtrasadas');
    tabelaContas.innerHTML = '';
    <% cont = @contasAtrasadas.count - 1
    while(cont >= 0)
    timer = @contasAtrasadas[cont].dataCompra
    data = timer.split(' ')[0].split('-')
    data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
    if @contasAtrasadas[cont].juros > 0
      @contasAtrasadas[cont].valor += (@contasAtrasadas[cont].juros/100) * @contasAtrasadas[cont].valor;
    end
    %>

    somarContasAtrasada( <%=@contasAtrasadas[cont].id %>, <%=@contasAtrasadas[cont].valor%>);

    tabelaContas.innerHTML = tabelaContas.innerHTML +
        "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
        "<div class='left col-1 colunaCorpoComum colunaIdConta'> <%= @contasAtrasadas[cont].id %> </div>" +
        "<div class='left col-1 colunaCorpoComum colunaCliente'> <%= Funcionario.pesquisaId(@contasAtrasadas[cont].funcionario)[0].nome %> </div>" +
        "<div class='left col-5 colunaCorpoComum colunaDescricao'> <%= @contasAtrasadas[cont].descricao %> </div>" +
        "<div class='left col-3 colunaCorpoComum colunaValor'> <%= @contasAtrasadas[cont].valor %> </div>" +
        "<div class='left col-3 colunaCorpoComum colunaData'> <%= data %> </div>" +
        "<div class='left col-3' style='width: 12.6%; font-size: 18px; margin-top: -43px;'>" +
        "<input style='zoom: 3;' type='checkbox' id='<%=@contasAtrasadas[cont].id%>' checked='checked' onchange='selecionarContaAtrasada(<%=@contasAtrasadas[cont].id%>, <%=@contasAtrasadas[cont].valor%>)'>" +
        "</div></div>";

    <% cont -= 1
    end %>

    tabelaContas = document.getElementById('tabelaContasDevendo');
    tabelaContas.innerHTML = '';
    <% cont = @contasDevendo.count - 1
    while(cont >= 0)
    timer =  @contasDevendo[cont].dataCompra
    data = timer.split(' ')[0].split('-')
    data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
    if @contasDevendo[cont].juros > 0
      @contasDevendo[cont].valor += (@contasDevendo[cont].juros/100) * @contasDevendo[cont].valor;
    end
    %>

    somarContasDevendo( <%=@contasDevendo[cont].id %>, <%=@contasDevendo[cont].valor%>);

    tabelaContas.innerHTML = tabelaContas.innerHTML +
        "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
        "<div class='left col-1 colunaCorpoComum colunaIdConta'> <%= @contasDevendo[cont].id %> </div>" +
        "<div class='left col-1 colunaCorpoComum colunaCliente'> <%= Funcionario.pesquisaId(@contasDevendo[cont].funcionario)[0].nome %> </div>" +
        "<div class='left col-5 colunaCorpoComum colunaDescricao'> <%= @contasDevendo[cont].descricao %> </div>" +
        "<div class='left col-3 colunaCorpoComum colunaValor'> <%= @contasDevendo[cont].valor %> </div>" +
        "<div class='left col-3 colunaCorpoComum colunaData'> <%= data %> </div>" +
        "<div class='left col-3' style='width: 12.6%; font-size: 18px; margin-top: -43px;'>" +
        "<input style='zoom: 3;' type='checkbox' id='<%=@contasDevendo[cont].id%>' checked='checked' onchange='selecionarContaAtrasada(<%=@contasDevendo[cont].id%>, <%=@contasDevendo[cont].valor%>)'>" +
        "</div></div>";

    <% cont -= 1
    end %>

  <%end %>

<% end %>

app/views/pagamentos/index.html.erb
<body>
<div id="wrap">
  <div id="masthead">
    <h1>Sistema Financeiro de Supermecado - Mercado São Caetano</h1>
    <h2><%= link_to 'Perfil', funcionarios_perfil_path %> | <%= link_to 'Contato', padrao_contato_path %> | <%= link_to 'Sair', logins_sair_path %></h2>
  </div>
  <div id="menucontainer">
    <div id="menu">
      <ul>
        <li><%= link_to 'Registro', new_contum_path %></li>
        <li><%= link_to 'Pagamento', pagamentos_path, class:"current" %></li>
        <li><%= link_to 'Contas', contums_path %></li>
        <li><%= link_to 'Cliente', clientes_path%></li>
        <%if Pessoa.getPessoaLogada.cargo == "gerente" %>
          <li><%= link_to 'Funcionário', funcionarios_path %></li>
        <%end%>
      </ul>
    </div>
  </div>
  <div id="container">

    <div id="content">

      <span class="titulo_formulario">
					Registrar um Pagamento
      </span>

      <% # formulario de pesquisa ......................................... %>
      <%= form_tag(pagamentos_path, method: :get, class:"formulario formulario_pesquisa") do %>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= text_field_tag :pesquisa, nil, class:"input100", placeholder:"Pesquise por nome, cpf e id" %>
          <span class="focus-input100"></span>
        </div>

        <div class="div_butao_formulario" style="margin-top: -70px; margin-left: 380px">
          <button class="botao_tabela" style="height: 50px">
						<span>
							Pesquisar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

      <% end %>

      <% # tabela de clientes..................................... %>
      <div class="col-12">
        <div class="menuTabela col-10 offset-1 row" style="width: 1133px;">
          <div class="left col-1 colunaTituloComum colunaId"> Id </div>
          <div class="left col-5 colunaTituloComum colunaNome"> Cliente </div>
          <div class="left col-3 colunaTituloComum colunaCpf"> Cpf </div>
          <div class="left col-3 colunaTituloComum colunaId"></div>
        </div>

        <div style="height: 200px; overflow-y:auto; overflow-x:hidden; background: #eeeeee;">
          <% @clientes.each do |cliente| %>
            <div class="menuTabela col-10 offset-1 row" style="width: 1140px; margin-left: 10px; background: #eeeeee;">
              <div class="left col-1 colunaCorpoComum colunaId"> <%= cliente.id %> </div>
              <div class="left col-5 colunaCorpoComum colunaNome"> <%= cliente.nome %> </div>
              <div class="left col-3 colunaCorpoComum colunaCpf"> <%= cliente.cpf %> </div>
              <div class="left col-3" style="width: 20%; font-size: 18px; margin-top: -20px;">
                <%= link_to 'Contas', pagamento_path(cliente), class:"botao_tabela", id:"d-#{'pagar-'+cliente.cpf}" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <%= form_with scope: :pagamento, remote:true, url:pagamentos_path, id:"formularioPagamento", class:"formulario" do |form| %>

        <input type="hidden" name="idsContasDevendo" id="idsContasDevendoSelecionadas" />

        <input type="hidden" name="idsContasAtrasada" id="idsContasAtrasadaSelecionadas" />

        <div class="elemento_formulario quantidade_elemento_linha_formulario_ficheiro">
          <span class="label-elemento_formulario" name="cliente">Cpf Cliente</span><br>
          <%= text_field_tag :cpf, nil, readonly:"true", id:"cpf", class:"input100", placeholder:"Cpf do cliente" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario_ficheiro">
          <span class="label-elemento_formulario" name="cliente">Nome do Cliente</span><br>
          <%= text_field_tag :nome, nil, readonly:"true", id:"nome", class:"input100", placeholder:"Nome do cliente" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario_ficheiro">
          <span class="label-elemento_formulario" name="valorConta">Valor Contas</span><br>
          <%= text_field_tag :valorContas, nil, id:'valorContas', readonly:"true", class:"input100", placeholder:"Valor das contas selecionadas" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario_ficheiro">
          <span class="label-elemento_formulario" name="valorConta">Valor Cliente</span><br>
          <%= text_field_tag :valorCliente, nil, id:"valorCliente", class:"input100", placeholder:"Valor dado pelo cliente" %>
          <span class="focus-input100"></span>
        </div>


        <div id="testeDiv" class='status_processo'></div>

        <div class="div_butao_formulario">
          <button class="botao_formulario" id="botaoPagar">
						<span>
							Pagar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

      <% end %>

      <%if @cliente.cpf != nil%>
        <script>selecionarCpfNomeCliente("<%=@cliente.nome%>","<%=@cliente.cpf%>")</script>
      <% end %>

      <% # tabela de contas atrazadas..................................... %>
      <textarea readonly=“true” id="contasAtrasada" class="titulo_formulario"></textarea>
      <script>setValorContaAtrasada(0)</script>
      <div class="col-12" style="width: 1140px" >
        <div class="menuTabela" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaIdConta"> Id </div>
          <div class="left col-1 colunaTituloComum colunaCliente"> Funcionário </div>
          <div class="left col-5 colunaTituloComum colunaDescricao"> Descrição </div>
          <div class="left col-3 colunaTituloComum colunaValor"> Valor </div>
          <div class="left col-3 colunaTituloComum colunaData"> Data de Compra </div>
          <div class="left col-3 colunaTituloComum " style="width: 12.6%"></div>
        </div>

        <div id="tabelaContasAtrasadas" style="width: 1200px; height: 200px; overflow-y:auto; overflow-x:hidden;">
          <script>setValorContaAtrasada(0)</script>
          <% cont = @contasAtrasadas.count - 1
             while(cont >= 0)
          %>
            <div class="menuTabela" style="width: 1140px; background: #ffffff;">
              <div class="left col-1 colunaCorpoComum colunaIdConta"> <%= @contasAtrasadas[cont].id %> </div>
              <div class="left col-1 colunaCorpoComum colunaCliente"> <%= Funcionario.pesquisaId(@contasAtrasadas[cont].funcionario)[0].nome %> </div>
              <div class="left col-5 colunaCorpoComum colunaDescricao"> <%= @contasAtrasadas[cont].descricao %> </div>
              <%if @contasAtrasadas[cont].juros > 0
                  @contasAtrasadas[cont].valor += (@contasAtrasadas[cont].juros/100) * @contasAtrasadas[cont].valor;
                end
              %>
              <div class="left col-3 colunaCorpoComum colunaValor"> <%= @contasAtrasadas[cont].valor %> </div>
              <%timer = @contasAtrasadas[cont].dataCompra
                data = timer.split(' ')[0].split('-')
                data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
              %>
              <div class="left col-3 colunaCorpoComum colunaData"> <%= data %> </div>
              <div class="left col-3" style="width: 12.6%; font-size: 18px; margin-top: -43px;">
                <input style="zoom: 3;" type="checkbox" id="<%=@contasAtrasadas[cont].id%>" checked='checked' onchange="selecionarContaAtrasada(<%=@contasAtrasadas[cont].id%>, <%=@contasAtrasadas[cont].valor%>)">
              </div>
            </div>
            <script>somarContasAtrasada(<%= @contasAtrasadas[cont].id %>, <%= @contasAtrasadas[cont].valor %>);</script>
          <% cont-= 1
             end %>
        </div>
      </div>

      <% # tabela de contas devendo..................................... %>
      <textarea readonly=“true” id="contasDevendo" class="titulo_formulario"></textarea>
      <script>setValorContaDevendo(0)</script>
      <div class="col-12" style="width: 1140px" >
        <div class="menuTabela" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaIdConta"> Id </div>
          <div class="left col-1 colunaTituloComum colunaCliente"> Funcionário </div>
          <div class="left col-5 colunaTituloComum colunaDescricao"> Descrição </div>
          <div class="left col-3 colunaTituloComum colunaValor"> Valor </div>
          <div class="left col-3 colunaTituloComum colunaData"> Data de Compra </div>
          <div class="left col-3 colunaTituloComum" style="width: 12.6%">Selecionar</div>
        </div>

        <div id="tabelaContasDevendo" style="width: 1200px; height: 200px; overflow-y:auto; overflow-x:hidden;">
          <script>setValorContaDevendo(0);</script>
          <% cont = @contasDevendo.count - 1
             while(cont >= 0)
          %>
            <div class="menuTabela" style="width: 1140px; background: #ffffff;">
              <div class="left col-1 colunaCorpoComum colunaIdConta"> <%= @contasDevendo[cont].id %> </div>
              <div class="left col-1 colunaCorpoComum colunaCliente"> <%= Funcionario.pesquisaId(@contasDevendo[cont].funcionario)[0].nome %> </div>
              <div class="left col-5 colunaCorpoComum colunaDescricao"> <%= @contasDevendo[cont].descricao %> </div>
              <%if @contasDevendo[cont].juros > 0
                  @contasDevendo[cont].valor += (@contasDevendo[cont].juros/100) * @contasDevendo[cont].valor;
                end
              %>
              <div class="left col-3 colunaCorpoComum colunaValor"> <%= @contasDevendo[cont].valor %> </div>
              <%timer = @contasDevendo[cont].dataCompra
                data = timer.split(' ')[0].split('-')
                data = data[2] + '/' + data[1] + '/' + data[0] + ' ' + timer.split(' ')[1]
              %>
              <div class="left col-3 colunaCorpoComum colunaData"> <%= data %> </div>
              <div class="left col-3" style="width: 12.6%; font-size: 18px; margin-top: -43px;">
                <input style="zoom: 3;" type="checkbox" id="<%=@contasDevendo[cont].id%>" checked='checked' onchange="selecionarContaDevendo(<%=@contasDevendo[cont].id%>, <%=@contasDevendo[cont].valor%>)">
              </div>
            </div>
            <script>somarContasDevendo(<%= @contasDevendo[cont].id %>, <%= @contasDevendo[cont].valor %>);</script>
          <% cont-= 1
             end %>
        </div>
      </div>

    </div>

  </div>
  <div id="footer"> Informações Sobre o Mercado </div>
</div>
</body>