config/routes.rb
Rails.application.routes.draw do

  get 'logins/index'

  get 'clientes/perfil'

  get 'logins/sair'

  get 'funcionarios/perfil'

  get 'padrao/contato'

  resources :funcionarios
  resources :contums
  resources :clientes
  resources :pagamentos
  resources :logins

  root 'logins#index'

end

app/models/funcionario.rb
class Funcionario < Pessoa
  validates :cargo, presence: {message: " nao pode ser em branco" }

  def self.pesquisa query
    funcionarios = listaFuncionarios;
    pesquisaIds = funcionarios.pesquisaId(query)
    pesquisaCpfs = funcionarios.pesquisaCpf(query)
    pesquisaNomes = funcionarios.pesquisaNome(query)
    resultado = []
    pesquisaIds.each do |funcionario|
      resultado << funcionario
    end
    pesquisaCpfs.each do |funcionario|
      if(!resultado.index(funcionario))
        resultado << funcionario
      end
    end
    pesquisaNomes.each do |funcionario|
      if(!resultado.index(funcionario))
        resultado << funcionario
      end
    end
    resultado
  end

  def self.listaFuncionarios
    funcionarios = listaFuncionariosAtivo
    funcionarios = funcionarios.listaFuncionariosAux
    funcionarios
  end

  scope :listaFuncionariosAux, -> { where("tipo like ?", "%#{1}%") }
  scope :listaFuncionariosAtivo, -> { where("inativo like ?", "%#{0}%") }
  scope :pesquisaId, ->(query) { where("id like ?", "%#{query}%") }
  scope :pesquisaCpf, ->(query) { where("cpf like ?", "%#{query}%") }
  scope :pesquisaNome, ->(query) { where("nome like ?", "%#{query}%") }
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  respond_to :js, :html

  @@resultadoPositivoFuncionario= ""

  def self.getResultadoPositivoFuncionario
    @@resultadoPositivoFuncionario
  end
  def self.setResultadoPositivoFuncionario valor
    @@resultadoPositivoFuncionario = valor
  end

  def perfil
    segurancaLogin(1)
    @funcionario = Pessoa.getPessoaLogada
  end

  def index
    segurancaLogin(11)
    @funcionario = Funcionario.new
    carregar_tabela(params[:pesquisa])

  end

  def new
    segurancaLogin(11)
    @funcionario = Funcionario.new
  end

  def edit
    segurancaLogin(11)
    @funcionario = Funcionario.find(params[:id])
    @funcionarios = Funcionario.listaFuncionarios
    render 'funcionarios/index'
  end

  def update
    id = nil
    if params[:id] == "perfil"
      segurancaLogin(1)
      id = Pessoa.getPessoaLogada.id
    else
      segurancaLogin(11)
      id = params[:id]
    end
    @funcionario = Funcionario.find(id)
    funcionarioAux = Funcionario.new(funcionario_params)
    if funcionarioAux.cargo != nil && funcionarioAux.cargo.downcase == "gerente"
      @@resultadoPositivoFuncionario = "erro-O sistema já tem um gerente"
      carregar_tabela ''
      render 'funcionarios/index'
    elsif @funcionario.update(funcionario_params)
      if params[:id] == "perfil"
        @@resultadoPositivoFuncionario = "Perfil Atualizado";
        Pessoa.setPessoaLogada(@funcionario)
        redirect_to funcionarios_perfil_path
      else
        @@resultadoPositivoFuncionario = "Funcionário Atualizado";
        redirect_to funcionarios_path
      end
    else
      if params[:id] == "perfil"
        render 'funcionarios/perfil'
      else
        carregar_tabela('')
        render 'funcionarios/index'
      end

    end

  end

  def create
    segurancaLogin(11)
    @funcionario = Funcionario.new(funcionario_params)
    # tipo = 0 é cliente e. tipo = 1 é funcionario
    @funcionario.tipo = 1
    @funcionario.inativo = 0

    if @funcionario.cargo.downcase == "gerente"
      @@resultadoPositivoFuncionario = "erro-O sistema já tem um gerente"
      carregar_tabela ''
      render 'funcionarios/index'
    elsif @funcionario.save
      @@resultadoPositivoFuncionario = "Funcionário salvo"
      redirect_to
    else
      carregar_tabela('')
      render 'funcionarios/index'
    end

  end

  def destroy
    segurancaLogin(11)
    @funcionario = Funcionario.find(params[:id])
    @funcionario.update(tipo: 0)
    @@resultadoPositivoFuncionario = "Funcionário Deletado";
    redirect_to funcionarios_path
  end

  private

  def segurancaLogin pessoa
    if pessoa == 1
      if Pessoa.getPessoaLogada() == nil || Pessoa.getPessoaLogada().tipo != 1
        redirect_to logins_path
      end
    elsif pessoa == 11
    if Pessoa.getPessoaLogada() == nil || Pessoa.getPessoaLogada().tipo != 1 || Pessoa.getPessoaLogada().cargo != "gerente"
      redirect_to logins_path
    end
    else
      if Pessoa.getPessoaLogada() == nil || Pessoa.getPessoaLogada().tipo != 0
        redirect_to logins_path
      end
    end
  end

  def funcionario_params
    params.require(:funcionario).permit(:nome, :cpf, :telefone, :celular, :email, :senha, :cidade, :rua, :numero, :cargo)
  end

  def carregar_tabela(pesquisa)
    if pesquisa && pesquisa != ''
      @funcionarios = Funcionario.pesquisa(pesquisa)
    else
      @funcionarios = Funcionario.listaFuncionarios
    end
  end

end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/index.html.erb
<body>
<div id="wrap">
  <div id="masthead">
    <h1>Sistema Financeiro de Supermecado - Mercado São Caetano</h1>
    <h2><%= link_to 'Perfil', funcionarios_perfil_path %> | <%= link_to 'Contato', padrao_contato_path %> | <%= link_to 'Sair', logins_sair_path %></h2>
  </div>
  <div id="menucontainer">
    <div id="menu">
      <ul>
        <li><%= link_to 'Registro', new_contum_path %></li>
        <li><%= link_to 'Pagamento', pagamentos_path %></li>
        <li><%= link_to 'Contas', contums_path %></li>
        <li><%= link_to 'Cliente', clientes_path %></li>
        <li><%= link_to 'Funcionário', funcionarios_path, class:"current" %></li>
      </ul>
    </div>
  </div>
  <div id="container">

    <div id="content">

      <% # formulario de cadastramento ..................................... %>
      <%= form_with model: @funcionario, scope: :funcionario, class:"formulario", local: true do |form| %>

        <span class="titulo_formulario">
					Cadastrar Funcionário
				</span>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :nome, class:"label-elemento_formulario" %><br>
          <%= form.text_field :nome, class:"input100", placeholder:"Digite um nome" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cpf, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cpf, class:"input100", placeholder:"Digite um cpf" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :telefone, class:"label-elemento_formulario" %><br>
          <%= form.text_field :telefone, class:"input100", placeholder:"Digite um número de telefone" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :celular, class:"label-elemento_formulario" %><br>
          <%= form.text_field :celular, class:"input100", placeholder:"Digite um número de celular" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :email, class:"label-elemento_formulario" %><br>
          <%= form.text_field :email, class:"input100", placeholder:"Digite um e-mail (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :senha, class:"label-elemento_formulario" %><br>
          <%= form.text_field :senha, type:"password", class:"input100", placeholder:"Digite uma senha (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cidade, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cidade, class:"input100", placeholder:"Digite o nome de uma cidade/Estado" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :rua, class:"label-elemento_formulario" %><br>
          <%= form.text_field :rua, class:"input100", placeholder:"Digite o nome de uma Rua" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :numero, class:"label-elemento_formulario" %><br>
          <%= form.text_field :numero, class:"input100", placeholder:"Digite o número da casa" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cargo, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cargo, class:"input100", placeholder:"Digite o um cargo" %>
          <span class="focus-input100"></span>
        </div>

        <% if(FuncionariosController.getResultadoPositivoFuncionario != "")
             valor = ""
             resultado = FuncionariosController.getResultadoPositivoFuncionario
             if resultado.split('-')[0] == 'erro'
               valor = "color: red"
               resultado = resultado.split('-')[1]
             end
        %>
          <span style="<%= valor %>" id="resultadoPositivo" class="status_processo">
            <%= resultado %>
          </span>
          <%FuncionariosController.setResultadoPositivoFuncionario("") %>
        <% end %>

        <div class="div_butao_formulario">
          <button class="botao_formulario">
						<span>
							Adicionar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>


        <% if @funcionario.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@funcionario.errors.count, "erros") %>
              antes de criar o funcionario:
            </h2>
            <ul>
              <% @funcionario.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


      <% end %>

      <% # formulario de pesquisa %>
      <%= form_tag(funcionarios_path, method: :get, remote:true, class:"formulario formulario_pesquisa") do %>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= text_field_tag :pesquisa, nil, class:"input100", placeholder:"Pesquise por nome, cpf e id" %>
          <span class="focus-input100"></span>
        </div>

        <div class="div_butao_formulario" style="margin-top: -70px; margin-left: 380px">
          <button class="botao_tabela" style="height: 50px">
						<span>
							Pesquisar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

      <% end %>

      <% # tabela de cadastramento..................................... %>
      <div class="col-12" >
        <div class="menuTabela col-10 offset-1 row" style="width: 1140px;">
          <div class="left col-1 colunaTituloComum colunaId"> Id </div>
          <div class="left col-5 colunaTituloComum colunaNome"> Nome </div>
          <div class="left col-3 colunaTituloComum colunaCpf"> Cpf </div>
          <div class="left col-3 colunaTituloComum colunaId"></div>
          <div class="left col-3 colunaTituloComum colunaId"></div>
        </div>

        <div id="tabelaFuncionario" style="height: 500px; overflow-y:auto; overflow-x:hidden;">

          <% @funcionarios.each do |funcionario| %>
            <% if funcionario.cargo != "gerente" %>
              <div class="menuTabela col-10 offset-1 row" style="width: 1140px; background: #ffffff;">
                <div class="left col-1 colunaCorpoComum colunaId"> <%= funcionario.id %> </div>
                <div class="left col-5 colunaCorpoComum colunaNome"> <%= funcionario.nome %> </div>
                <div class="left col-3 colunaCorpoComum colunaCpf"> <%= funcionario.cpf %> </div>
                <div class="left col-3" style="width: 10%; font-size: 18px; margin-top: -20px;">
                  <%= link_to 'Editar', edit_funcionario_path(funcionario), class:"botao_tabela",id:"d-#{'edit-'+funcionario.cpf}" %>
                </div>
                <div class="left col-3" style="width: 10%; font-size: 18px; margin-top: -20px;">
                  <%= link_to 'Deletar', funcionario_path(funcionario), class:"botao_tabela",
                              method: :delete,
                              data: { confirm: 'Tem certeza que deseja excluir esse Funcionário?' }, id:"d-#{'delete-'+funcionario.cpf}"%>

                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>

  </div>
  <div id="footer"> Mercado São Caetano - Centro do povoado Quandu, municipio de Poço de Trincheiras </div>
</div>
</body>

app/views/funcionarios/index.js.erb
var tabelaFuncionario = document.getElementById('tabelaFuncionario');
tabelaFuncionario.innerHTML = '';

<% @funcionarios.each do |funcionario| %>

tabelaFuncionario.innerHTML = tabelaFuncionario.innerHTML +
    "<div class='menuTabela' style='width: 1140px; background: #ffffff;'>" +
    "<div class='left col-1 colunaCorpoComum colunaId'> <%= funcionario.id %> </div>" +
    "<div class='left col-1 colunaCorpoComum colunaNome'> <%= funcionario.nome %> </div>" +
    "<div class='left col-5 colunaCorpoComum colunaCpf'> <%= funcionario.cpf %> </div>" +
    "<div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
    "<a href=<%=edit_funcionario_path(funcionario)%> class='botao_tabela' id=<%="d-#{'edit-'+funcionario.cpf}"%> >Editar</a>" +
    "</div><div class='left col-3' style='width: 10%; font-size: 18px; margin-top: -20px;'>" +
    "<a class='botao_tabela' id=<%="d-#{'delete-'+funcionario.cpf}"%> data-confirm='Tem certeza que deseja excluir esse Cliente?' rel='nofollow' data-method='delete' href=<%= funcionario_path(funcionario) %>>Deletar</a>" +
    "</div></div>";

<% end %>

app/views/funcionarios/perfil.html.erb
<body>
<div id="wrap">
  <div id="masthead">
    <h1>Sistema Financeiro de Supermecado - Mercado São Caetano</h1>
    <h2><%= link_to 'Perfil', funcionarios_perfil_path %> | <%= link_to 'Contato', padrao_contato_path %> | <%= link_to 'Sair', logins_sair_path %> </h2>
  </div>
  <div id="menucontainer">
    <div id="menu">
      <ul>
        <li><%= link_to 'Registro', new_contum_path %></li>
        <li><%= link_to 'Pagamento', pagamentos_path %></li>
        <li><%= link_to 'Contas', contums_path %></li>
        <li><%= link_to 'Cliente', clientes_path %></li>
        <li><%= link_to 'Funcionário', funcionarios_path %></li>
      </ul>
    </div>
  </div>
  <div id="container">

    <div id="content">

      <% # formulario de cadastramento ..................................... %>
      <%= form_with model: @funcionario, scope: :funcionario, url:funcionarios_perfil_path, class:"formulario", local: true do |form| %>

        <span class="titulo_formulario">
					Atualizar Perfil
				</span>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :nome, class:"label-elemento_formulario" %><br>
          <%= form.text_field :nome, class:"input100", placeholder:"Digite um nome" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cpf, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cpf, class:"input100", placeholder:"Digite um cpf" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :telefone, class:"label-elemento_formulario" %><br>
          <%= form.text_field :telefone, class:"input100", placeholder:"Digite um número de telefone" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :celular, class:"label-elemento_formulario" %><br>
          <%= form.text_field :celular, class:"input100", placeholder:"Digite um número de celular" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :email, class:"label-elemento_formulario" %><br>
          <%= form.text_field :email, class:"input100", placeholder:"Digite um e-mail (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :senha, class:"label-elemento_formulario" %><br>
          <%= form.text_field :senha, type:"password", class:"input100", placeholder:"Digite uma senha (mínimo de 5 carecteres)" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :cidade, class:"label-elemento_formulario" %><br>
          <%= form.text_field :cidade, class:"input100", placeholder:"Digite o nome de uma cidade/Estado" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :rua, class:"label-elemento_formulario" %><br>
          <%= form.text_field :rua, class:"input100", placeholder:"Digite o nome de uma Rua" %>
          <span class="focus-input100"></span>
        </div>

        <div class="elemento_formulario quantidade_elemento_linha_formulario">
          <%= form.label :numero, class:"label-elemento_formulario" %><br>
          <%= form.text_field :numero, class:"input100", placeholder:"Digite o número da casa" %>
          <span class="focus-input100"></span>
        </div>

        <% if(FuncionariosController.getResultadoPositivoFuncionario != "")
             valor = ""
             resultado = FuncionariosController.getResultadoPositivoFuncionario
             if resultado.split('-')[0] == 'erro'
               valor = "color: red"
               resultado = resultado.split('-')[1]
             end
        %>
          <span style="<%= valor %>" id="resultadoPositivo" class="status_processo">
            <%= resultado %>
          </span>
          <%FuncionariosController.setResultadoPositivoFuncionario("") %>
        <% end %>


        <div class="div_butao_formulario">
          <button class="botao_formulario">
						<span>
							Atualizar
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
          </button>
        </div>

        <% if @funcionario.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@funcionario.errors.count, "erros") %>
              antes de criar o cliente:
            </h2>
            <ul>
              <% @funcionario.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <% end %>
    </div>
  </div>
  <div id="footer"> Mercado São Caetano - Centro do povoado Quandu, municipio de Poço de Trincheiras </div>
</div>
</body>